# Generated by Django 5.1.4 on 2024-12-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongestionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('person_count', models.IntegerField()),
                ('coordinates', models.JSONField()),
                ('congestion_level', models.CharField(max_length=20)),
                ('area', models.CharField(default='main', max_length=50)),
            ],
        ),
    ]
