# Generated by Django 5.1.4 on 2024-12-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_congestiondata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congestiondata',
            name='area',
        ),
        migrations.AlterField(
            model_name='congestiondata',
            name='congestion_level',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='congestiondata',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images/%Y/%m/%d/'),
        ),
    ]
